### ISSUE TITLE
[1.18.2] FallingIcicleEntity can cause crashes!

### ISSUE THREAD

**Issue by MSandro** [AstralOrdana/Immersive-Weathering#111]
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/26/22, 12:03 PM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class net.minecraft.class_1747 (net.minecraft.class_1739 and net.minecraft.class_1747 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3dd3bcd)
	at net.minecraft.block.SlabBlock.handler$gam000$canReplace(SlabBlock:595)
	at net.minecraft.block.SlabBlock.canReplace(SlabBlock)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.canReplace(AbstractBlock:963)
	at net.minecraft.item.ItemPlacementContext.<init>(ItemPlacementContext:32)
	at net.minecraft.item.AutomaticItemPlacementContext.<init>(AutomaticItemPlacementContext:15)
	at net.minecraft.entity.FallingBlockEntity.tick(FallingBlockEntity:164)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:9091)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2482.handler$gam000$canReplace(class_2482.java:595)
	at net.minecraft.class_2482.method_9616(class_2482.java)
	at net.minecraft.class_4970$class_4971.method_26166(class_4970.java:963)
	at net.minecraft.class_1750.<init>(class_1750.java:32)
	at net.minecraft.class_2968.<init>(class_2968.java:15)
	at net.minecraft.class_1540.method_5773(class_1540.java:164)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:9091)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:falling_icicle (com.ordana.immersive_weathering.registry.entities.FallingIcicleEntity)
	Entity ID: 13484
	Entity Name: entity.minecraft.falling_icicle
	Entity's Exact location: -6.50, 61.50, -26.50
	Entity's Block location: World: (-7,61,-27), Section: (at 9,13,5 in -1,3,-2; chunk contains blocks -16,-64,-32 to -1,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Air:300s,BalmData:{},BlockState:{Name:"immersive_weathering:icicle",Properties:{thickness:"tip",vertical_direction:"down",waterlogged:"false"}},DropItem:1b,FallDistance:0.0f,FallHurtAmount:6.0f,FallHurtMax:40,Fire:-1s,HurtEntities:1b,Invulnerable:0b,KubeJSPersistentData:{},Motion:[0.0d,0.0d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[-6.5d,61.5d,-26.5d],Rotation:[0.0f,0.0f],Time:12,UUID:[I;-842821260,145378144,-2030501879,625139884],cardinal_components:{"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0}},cpaCooldown:0,cpadidTP:0b}
	Immitating BlockState: Block{immersive_weathering:icicle}[thickness=tip,vertical_direction=down,waterlogged=false]
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:9091)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MSandro'/9447, l='ServerLevel[gregor]', x=-4.21, y=65.50, z=-16.55]]
	Chunk stats: 2401
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,71,6), Section: (at 8,7,6 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 29455045 game time, 15678584 day time
	Level name: gregor
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 32682 (now: false), thunder time: 32944 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 4.18.0-373.el8.x86_64
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2833788432 bytes (2702 MiB) / 4638900224 bytes (4424 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7702P 64-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16073.22
	Virtual memory used (MB): 8435.52
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 17 total; -Xms4G -Xmx12G -Xmn768m -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.5
		adorn: Adorn 3.5.0+1.18.2
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.11
		ae2: Applied Energistics 2 11.1.4
		ae2additions: AEAdditions 3.1.2-fabric
		ae2things: AE2Things 1.1.0-beta.8
		ae2wtlib: AE2WTLib 11.1.4
		agape_space: Space Dimensions 0.5.15
		alloy_forgery: Alloy Forgery 2.0.13+1.18
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		appbot: Applied Botanics 1.3.1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		arcanus: Arcanus 1.29
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.6.77
		artis: Artis-Recrafted 2.4.1+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		attributefix: AttributeFix 14.0.2
		auto-workstations: Auto Workstations 1.0-SNAPSHOT-14
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.1.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		beaconoverhaul: Beacon Overhaul 1.6.0+1.18.2
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bewitchment: Bewitchment 1.18-23
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.4.1
			playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		blabber: Blabber 0.2.0
		blockus: Blockus 2.4.7+1.18.2
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bookshelf: Bookshelf 13.2.46
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.8-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		botania: Botania 1.18.2-434-FABRIC
		buildinggadgets: st'ructure tools 1.0.22
			mm: Manningham Mills 2.3
		cacao: Croptopia's Chocolaterie 1.2
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		carrier: Carrier 1.10.0
		catwalksinc: Catwalks Inc. 1.3.0
		celib: Celib 1.0.0
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chisel: Chisel Refabricated 1.4.5
		chiselsandbits: Chisels & Bits 1.2.113
		clickadv: Clickable Advancements Mod 2.6
		clickmachine: Kenza's Click Machine 1.2.0
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+13
		collective-fabric: Collective (Fabric) 4.27
		compress: Compress 'em [v1.5]
		computercraft: CC: Restitched 1.100.8
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
		conjuring: Conjuring 1.0.22+1.18
		connectivity: Connectivity Mod 1.18.2-3.3
		coxinhautilities: Coxinha Utilities 1.4+1.18.2
			omega-config-gui: Omega Config GUI 1.2.3-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
		craftingtweaks: Crafting Tweaks 14.0.3
		crawl: Crawl 0.10.6
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		createaddition: Create Crafts & Additions ${version}
		createplus: CreatePlus 1.0
		croparia: Croparia 3.8.3
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		croptosis: Croptosis 1.5.0
		customspawns: Custom Spawns 0.6+1.18
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
			autoconfig1u: Auto Config v1 Updated 3.2.2
		dankstorage: Dank Storage 1.18.2-3.7.1
		dark-enchanting: Dark Enchanting 1.0.0+1.18.2
		darkutils: DarkUtilities 10.0.5
		datapackportals: Datapack Portals 1.1.1-1.18
			blue_endless_jankson: jankson 1.2.1
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		dawn: Dawn API 3.3.2
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.4
			maybe-data: Maybe data 1.3.1-1.18.2
		dml-refabricated: Deep Mob Learning: Refabricated 1.18.2
			dml-refabricated-base: DML: Refabricated - Base 1.18.2
			dml-refabricated-events: DML: Refabricated - Vanilla Events 1.18.2
			dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 1.18.2
			dml-refabricated-rei: DML: Refabricated - REI Integration 1.18.2
			ktdatataglib: KtDataTagLib 1.6.5+1.18.2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.4-beta
		doubledoors-fabric: Double Doors (Fabric) 3.3
		dragonfight: Dragonfight Mod 1.18.2-2.5
		dragonloot: DragonLoot 1.1.0
		dramaticdoors: Dramatic Doors (Fabric) 1.18.2-1.1.1
		dripstonenerf: NoDrip (FABRIC) 1.0
		dusk: Dusk Mod 1.18.2-2.1
		edenring: EdenRing 0.5.2
		ellemes_container_lib: Ellemes' Container Library 1.4.0-beta.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.4.1
		endrem: End Remastered 5.1.0
		enhancedcelestials: Enhanced Celestials 2.0.7
		evs-betterend: Enchanted Vertical Slabs - BetterEnd Edition 1.0.0
		expandedstorage: Expanded Storage 7.4.0-beta.4
		experiencebugfix: Experience Bug Fix 18
		extended_drawers: Extended Drawers 1.3.1+mc.1.18.2
			graphlib: Graph Lib 0.2.4+1.18.2
			mconfig: Mconfig 1.2.0
				de_poiu_apron_apron: apron 2.1.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extraalchemy: Extra Alchemy 1.8.1
		extractinatortweaks: Extractinator Tweaks 1.0-SNAPSHOT-3
		extragenerators: Extra Generators 1.2.1-BETA+1.18
		extraorigins: Extra Origins 1.18-12
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.1
		fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricaeexnihilo: FabricaeExNihilo 0.1.6+mc1.18.2
		fabrication: Fabrication 3.0+1.18
			pride: Pride Lib 1.1.0+1.17
		fabricloader: Fabric Loader 0.14.8
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		farmingforblockheads: Farming for Blockheads 10.0.2
		fastload: Fast Load 1.1.5
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		fertilization: Fertilization 8.0.0
		findme: FindMe 3.0.6
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgero: Forgero 0.9.5-BETA-1.18.2
		ftbchunks: FTB Chunks 1802.3.6-build.147
		ftblibrary: FTB Library 1802.3.6-build.123
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		ftbultimine: FTB Ultimine 1802.3.3-build.55
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		geckolib3: Geckolib 3.0.51
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.5.0-1.18.2
		gobber2: Gobber2 2.5.79
			pugh_lib: Pugh Lib 1.3.2
			pugh_tools: Pugh Tools 1.2.7
		harvest_scythes: Harvest Scythes 2.5.1
		heartytrinkets: Hearty Trinkets 1.18.2-1.0.0
		horizontalpanes: Horizontal Panes 1.1.7+1.18.2
		iceberg: Iceberg 1.0.38
		immersive_weathering: Immersive Weathering 2.5.6
		improved-stations: Improved Stations 2.1.0
		indrev: Industrial Revolution 1.14.0-BETA
			fake-player-api: Fake Player API 0.3.0
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		inmis: Inmis 2.6.0-1.18.2
		inventorio: Inventorio 1.7.0
		inventorysorter: Inventory Sorter 1.8.8-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
		iron-jetpacks: Iron Jetpacks 0.4.3
		itemfilters: Item Filters 1802.2.7-build.33
		java: OpenJDK 64-Bit Server VM 17
		jmi: JourneyMapIntegration 0.12-22
		journeymap-fabric: Journeymap 5.8.5
			journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		justenoughkeys: Just Enough Keys 0.5.3
		kibe: Kibe 1.9.9-BETA+1.18
		kjsextras: KubeJS Extras 3.0.0
		kleeslabs: KleeSlabs 11.1.1
		konkrete: Konkrete 1.4.0
		kubejs: KubeJS 1802.5.4-build.524
		kubejs_botania: KubeJS Botania 1.0.2
		kubejs_create: KubeJS Create 1802.2.2-build.26
		lanoperators: LAN Operators 1.0.0
		lazydfu: LazyDFU 0.1.2
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.7.10
		locki: Locki 0.6.3
		lychee: Lychee Tweaker 2.2.8
		mambience: MAmbience 5.0.0+1.18.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 7.8.0
			megane-alloy-forgery: megane-alloy-forgery 7.8.0
			megane-api: megane-api 7.8.0
			megane-applied-energistics-2: megane-applied-energistics-2 7.8.0
			megane-create: megane-create 7.8.0
			megane-deep-mob-learning-simulacrum: megane-deep-mob-learning-simulacrum 7.8.0
			megane-extra-generators: megane-extra-generators 7.8.0
			megane-fabric-transfer: megane-fabric-transfer 7.8.0
			megane-industrial-revolution: megane-industrial-revolution 7.8.0
			megane-kibe: megane-kibe 7.8.0
			megane-lib-block-attributes: megane-lib-block-attributes 7.8.0
			megane-modern-dynamics: megane-modern-dynamics 7.8.0
			megane-reborn-core: megane-reborn-core 7.8.0
			megane-reborn-energy: megane-reborn-energy 7.8.0
			megane-runtime: megane-runtime 7.8.0
			megane-tech-reborn: megane-tech-reborn 7.8.0
			megane-vanilla: megane-vanilla 7.8.0
			megane-wireless-networks: megane-wireless-networks 7.8.0
		memoryleakfix: Memory Leak Fix 1.18.2-0.5.4
		minecarttweaks: Cammie's Minecart Tweaks 1.5
		minecraft: Minecraft 1.18.2
		mixin-conflict-helper: Mixin Conflict Helper 1.1.0
		mo_glass: Mo Glass 1.6.1-MC1.18.2
		mobscarecrow: Mob Scarecrow 2.1.1
		modern_industrialization: Modern Industrialization 1.2.2
			magna: Magna 1.7.0-1.18-pre1
		moderndynamics: Modern Dynamics 0.2.4-beta
		morezombievillagers-fabric: More Zombie Villagers (Fabric) 1.5
		mostructures: Mo' Structures 1.4.2+1.18.2
		mystical_index: Mystical Index 1.18.2-0.0.10
			stacc: Stacc 1.3.0
		mythicmounts: Mythic Mounts 1.18.2-7.0
		netherportalfix: NetherPortalFix 9.0.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		nounusedchunks: No Unused Chunks 1.1
		observable: Observable 2.2.3
		onastick: On A Stick 2.0.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				calio: Calio 1.5.1
		origins-classes: Origins: Classes 1.3.0
		owo: oωo 0.7.2-no-cme+1.18
		patchouli: Patchouli 1.18.2-71.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		peripheralium: Peripheralium 0.1.1
		peripheralworks: Unlimited Peripheral Works 0.1.2
		phosphor: Phosphor 0.8.1
		pickablevillagers: Pickable Villagers 1.2.0+1.18.2
		pigpen: PigPen 8.0.1
		plantinajar: Plant In A Jar 2.3.1
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
			org_objenesis_objenesis: objenesis 3.2
		platforms: Platforms 1.2.5
		polymorph: Polymorph 0.0.21-1.18.2
		probejs: ProbeJS 3.2.0
		puzzleslib: Puzzles Lib 3.3.5
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7
		reborncore: Reborn Core 5.2.0
		redbits: Red Bits 1.13.3
			interference: Interference API 1.4.1
		redstonebits: Redstone Bits 1.8.2
		refabslab: Refabricated Slabs 0.7.2+1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
		regrowth: Regrowth 0.30d.release
		remote_controlled: Remote Controlled 0.0.6-1.18.2
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		respro: Resource Provider Library 0.2.2+1.18.2
		rhino: Rhino 1802.1.14-build.206
		roughlyenoughitems: Roughly Enough Items 8.3.510
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		rswires: RSWires 4.13.0
			hctm-base: HCTM Base 3.8.0
				qcommon-cfg-core: qcommon-cfg-core 3.3.0
				qcommon-croco: Croco 2.1.1
		runelic: Runelic 11.0.1
		seasons: Fabric Seasons 1.4-BETA+1.18
		secretrooms: Secret Rooms 1.3.1+1.18.2
		shetiphiancore: ShetiPhianCore 1.2.13
			myron: Myron 1.6.3+1.18.1
		simple-rpc: Simple RPC 3.1.0
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.0.1
		simpleteleporters: Simple Teleporters 2.3.0
		simplevoidworld: Simple Void World 4.0.0
		skyislands: skyislands 1.0
		sleepwarp: SleepWarp 1.1.1+1.18.2
		smallernetherportals-fabric: Smaller Nether Portals (Fabric) 1.8
		soaringstructures2: Soaring Structures 2 1.18.2 - 2.3.1
		someforgepatchesported: Some Forge Patches Ported 1.0.3
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		soundmuffler: Soundmuffler 1.0.0
		spark: spark 1.9.11
		spatialharvesters: Spatial Harvesters 0.11.13c
			completeconfig: CompleteConfig 1.3.3
		spectrum: Spectrum 1.4.2-1.18.2-chaos_and_exploration
			additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
			bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
			incubus_core: Incubus Core 1.7-rc.4
		strawdummy: Straw Dummy 1.7.0
		structure_floaters: structure_floaters ${version}
		suggestion_tweaker: Suggestion Tweaker 1.18.2-1.2.0
		techreborn: Tech Reborn 5.2.0
			team_reborn_energy: Energy 2.2.0
		terrarianslimes: Terrarian Slimes 1.2.1-BETA+1.18
		the_extractinator: The Extractinator 1.0.8
		things: Things 0.2.18+1.18
		timeinabottle: Time in a Bottle 1.6.1-mc1.18.2-fabric
		toms_storage: Tom's Simple Storage Mod 1.3.4
		toolleveling: ToolLeveling+ 1.18.2 - 1.3.3
		totemmod: Wither Totems Mod 0.3.5-1.18.2-pre2
		tradingpost: Trading Post 3.2.0
		trapexpansion: Trap Expansion 1.3.3
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.3
		trinkets: Trinkets 3.3.1
		turtlematic: Turtlematic 0.4.3
		twigs: Twigs 1.1.3-patch2+1.18.2
		twilightforest: The Twilight Forest 4.1.251
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 1.1.342-beta+1.18.2-dev.dd61cdc
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
		upc: UPC 0.0.2
		voidcrafting: Void Crafting 1.6.4+fabric-1.18.2
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		wands: Building Wands 2.6_beta
		waystones: Waystones 2.5.5+mc1.18.2
		wireless_redstone: Wireless Redstone 2.0.5
		wirelessnetworks: Wireless Networks 1.5.1
		wthit: wthit 4.11.0
		xps: Xp Obelisk 0.4.2.r_for_1.18.x_Fabric
		yigd: You're in Grave Danger 1.3.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Server Running: true
	Player Count: 1 / 20; [class_3222['MSandro'/9447, l='ServerLevel[gregor]', x=-4.21, y=65.50, z=-16.55]]
	Data Packs: vanilla, minecraft/croptop, createplus/createplus-core, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: None
```

**Comment by MSandro** [comment]
it was caused by RefabSlab
https://github.com/CebbysMods/refabslab-mod/issues/22
