### ISSUE TITLE
compatibility issue with RelicEx | 1.19 fabric

### ISSUE THREAD

**Issue by Surpos0** [AstralOrdana/Immersive-Weathering#116]
Game is saying that im on wrong version of cloth config, but when i delete RelicEx, game starts as normal. with no changes of cloth config.

**Comment by Surpos0** [comment]
relicex-3.2.3
cloth-config-8.0.75-fabric
immersive_weathering-1.0.1-1.19

fabric loader log:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Weathering' (immersive_weathering) 1.0.1-1.19_SNAPSHOT with any version that is compatible with:
		 - cloth-config 8.0.75
Unmet dependency listing:
	 - Mod 'Immersive Weathering' (immersive_weathering) 1.0.1-1.19_SNAPSHOT requires any 7.x version of mod 'Cloth Config v8' (cloth-config), which can't be loaded due to other constraints!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:213)
	at crystallauncher.MineClient.main(MineClient.java:36)

**Comment by lxly9** [comment]
change it in the fabric.mod.json

**Comment by lxly9** [comment]
change the cloth config dependency to 8.0.x and if you have any modded leaves, turn off the leaf particle in the iw's config

**Comment by lxly9** [comment]
it'll crash every time you get close to leaves if you dont do that lol
