### ISSUE TITLE
Comprehensive Issue regarding particles from leaves

### ISSUE THREAD

**Issue by lxly9** [AstralOrdana/Immersive-Weathering#124]
My self-built modpack suffered from a crash whenever looking at modded leaves. The issue was the particles from the modded leaves. The error was fixed when disabling leaf particles in the config. I painstakingly byte searched my mods folder. I tried every single mod afterwards with Immersive weathering and the error persisted. 
This is the error code I got each time i tried to join a world (when standing near them) or created a world and got near them.

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2394.method_10295()" because "$$0" is null
    at net.minecraft.class_638.method_8406(class_638.java:607)
    at net.minecraft.class_5945.method_34681(class_5945.java:63)
    at net.minecraft.class_5945.method_41305(class_5945.java:23)
    at net.minecraft.class_5945.method_34682(class_5945.java:16)
    at net.minecraft.class_2397.handler$dep000$randomDisplayTick(class_2397.java:1566)
    at net.minecraft.class_2397.method_9496(class_2397.java)
    at net.minecraft.class_638.method_2943(class_638.java:383)
    at net.minecraft.class_638.method_2941(class_638.java:359)
    at net.minecraft.class_310.method_1574(class_310.java:1892)
    at net.minecraft.class_310.method_1523(class_310.java:1135)
    at net.minecraft.class_310.method_1514(class_310.java:768)
    at net.minecraft.client.main.Main.method_44604(Main.java:244)
    at net.minecraft.client.main.Main.main(Main.java:51)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I'll also link you my latest.log
[latest (3).log](https://github.com/AstralOrdana/Immersive-Weathering/files/9600522/latest.3.log)

**Comment by AstralOrdana** [comment]
we cant help you if you dont specify which version you are playing
