### ISSUE TITLE
When you place belladonna from bewitchment on mulch it crashes my server

### ISSUE THREAD

**Issue by Dannieboi** [AstralOrdana/Immersive-Weathering#219]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version:
Immersive Weathering version:
Moonlight Lib version:
Fabric API / QSL / Forge version:

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
java.lang.IllegalArgumentException: Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{bewitchment:belladonna}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.ordana.immersive_weathering.blocks.soil.MulchBlock.method_9514(MulchBlock.java:99)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923)
	at net.minecraft.class_3218.redirect$eha000$redirectBlockStateTick(class_3218.java:17671)
	at net.minecraft.class_3218.method_18203(class_3218.java:486)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place Mulch
2. Place Belladonna
3. Let it grow and boom the server is down

**Expected behavior:**
The belladonna to grow like a normal crop

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by VonZeeple** [comment]
I have the exact same issue with tomatoes from Farmers Delight

**Comment by AstralOrdana** [comment]
this was fixed in a recent update
