### ISSUE TITLE
Crashing My Server

### ISSUE THREAD

**Issue by ereese99** [AstralOrdana/Immersive-Weathering#234]
[15:11:26] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_39934(class_3898.java:693) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[15:11:26] [Worker-Main-7/ERROR]: Requested chunk : 11 41
[15:11:26] [Worker-Main-7/ERROR]: Region bounds : 1 24 | 17 40
[15:11:27] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_39934(class_3898.java:693) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[15:11:27] [Worker-Main-13/ERROR]: Failed to light chunk [6, 33]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:695) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[15:11:27] [Worker-Main-13/ERROR]: Failed to light chunk [4, 33]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:695) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[15:11:27] [Worker-Main-13/ERROR]: Failed to light chunk [5, 33]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:695) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
[15:11:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Feature placement
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 11 41
	at net.minecraft.class_3233.method_8402(class_3233.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_8624(class_3233.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[15:11:27] [Server thread/ERROR]: This crash report has been saved to: C:\Users\erees\curseforge\minecraft\Instances\Future Fabric\crash-reports\crash-2023-02-02_15.11.27-server.txt
[15:11:27] [Server thread/INFO]: [STDOUT]: Saving server results
[15:11:27] [Server thread/INFO]: Stopping server
[15:11:27] [Server thread/INFO]: Saving players

**Comment by PutridNonsense** [comment]
do you have any other mods on your server?
