### ISSUE TITLE
Incompatibility: WeatherState does not exist in Block (RefabricatedSlabs)

### ISSUE THREAD

**Issue by No3371** [AstralOrdana/Immersive-Weathering#248]
**Describe the bug:**
[RefabricatedSlabs](https://beta.curseforge.com/minecraft/mc-mods/refabricated-slabs) is a mod that allow mixing slabs when building.  Mixing IW slabs results in crash. It seems like when a IW slab get replaced by RS, IW still consider it a IW slab.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.19.2-1.2.8
Moonlight Lib version:  1.19.2-2.2.7
Fabric API / QSL / Forge version: 0.14.14

**Logs:**
```
java.lang.IllegalArgumentException: Cannot set property class_2754{name=weathering, clazz=class com.ordana.immersive_weathering.blocks.Weatherable$WeatheringState, values=[FALSE, TRUE, STABLE]} as it does not exist in Block{refabslab:double_slab_block}
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at com.ordana.immersive_weathering.blocks.Weatherable.getWeatheredStateForPlacement(Weatherable.java:57)
	at com.ordana.immersive_weathering.blocks.mossable.MossableSlabBlock.method_9605(MossableSlabBlock.java:39)
	at net.minecraft.class_1747.method_7707(class_1747.java:119)
	at net.minecraft.class_1747.method_7712(class_1747.java:71)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:366)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.accurateblockplacement_DoItemUseBypassDisable(class_310.java:5459)
	at net.minecraft.class_757.handler$zic000$onUpdateTargetedEntityComplete(class_757.java:3358)
	at net.minecraft.class_757.method_3190(class_757.java:637)
	at net.minecraft.class_757.method_3188(class_757.java:994)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**To Reproduce:**
Put any slab on IW slabs.

**Comment by No3371** [comment]
#249 Tested in game, seems working.
