### ISSUE TITLE
Incompatibility with Restricted Portals -- Server gets stuck in a resources reload loop

### ISSUE THREAD

**Issue by NerjalNosk** [AstralOrdana/Immersive-Weathering#268]
**Describe the bug:**
Game (server) gets stuck in a resource loading loop, and only crashes with a StackOverflow

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.9
Moonlight Lib version: 2.2.31
Fabric API / QSL / Forge version: Fabric API 0.76.0+1.19.2

**Other mods:**

```
- ad_astra 1.12.6
- adorn 3.8.1+1.19.2
- advanced_runtime_resource_pack 0.6.4
- advdebug 2.3.0
- ae2 12.9.3
\-- noindium 1.1.0+1.19
- ae2wtlib 12.8.5
- alloy_forgery 2.0.20+1.19
- amplified_nether 1.2.1
- angling 1.0.1
- appleskin 2.4.1+mc1.19
- architectury 6.5.77
- badpackets 0.2.1
- badstdout 1.1.1-1.19
- balm-fabric 4.5.7
- bedspreads 6.0.0+1.19.2
- betteranimalsplus 1.19.2-11.0.10
- bettercombat 1.6.2+1.19
- betterdeserttemples 1.19.2-Fabric-2.2.2
\-- org_reflections_reflections 0.10.2
- betterdungeons 1.19.2-Fabric-3.2.1
- bettermineshafts 1.19.2-Fabric-3.2.0
- betteroceanmonuments 1.19.2-Fabric-2.1.0
- betterstats 2.4+1.19.2
\-- tcdcommons 2.4+1.19.2
- bigendcitiesmod 1.19.3-1.0.0
- biomemakeover 1.19.2-1.6.4
- bitsandchisels 2.7.0
\-- stacc 1.3.4
- blahaj 0.2.0
- block_limit_fix 1.0.3-fabric
- bosses_of_mass_destruction 1.4.6-1.19.2
|-- maelstrom_library 1.3-1.19-pre1
\-- multipart_entities 1.2-1.19-pre1
- botania 1.19.2-438-FABRIC
|-- fiber 0.23.0-2
|-- reach-entity-attributes 2.3.0
\-- step-height-entity-attribute 1.0.0
- botarium 1.8.2
- cacao 1.2
- cardinal-components 5.0.2
|-- cardinal-components-base 5.0.2
|-- cardinal-components-block 5.0.2
|-- cardinal-components-chunk 5.0.2
|-- cardinal-components-entity 5.0.2
|-- cardinal-components-item 5.0.2
|-- cardinal-components-level 5.0.2
|-- cardinal-components-scoreboard 5.0.2
\-- cardinal-components-world 5.0.2
- carpeted 1.19.2-1.4
- carpettrapdoors 1.1
- chisel 1.4.6
- chorus_links 1.6.0
- chunky 1.3.38
- cinderscapes 3.0.3
|-- cinderscapes-client 3.0.3
|-- cinderscapes-common 3.0.3
\-- cinderscapes-worldgen 3.0.3
- cleanview 1.19.2-v1-fabric
- cloth-config 8.2.88
\-- cloth-basic-math 0.6.1
- collective 6.53
- combatroll 1.1.5+1.19
- command_structures 3.1.0+1.19
- continents 1.1.2
- corgilib 1.0.0.32
|-- com_electronwill_night-config_core 3.6.6
\-- com_electronwill_night-config_toml 3.6.6
- craftycuisine 1.2.0
- create 0.5.0.i-991+1.19.2
|-- com_google_code_findbugs_jsr305 3.0.2
|-- flywheel 0.6.8.a-4
|-- milk 1.0.51
| \-- dripstone_fluid_lib 2.0.1
|-- porting_lib 2.1.875+1.19.2
| |-- forge_tags 3.0
| |-- porting_lib_accessors 2.1.875+1.19.2
| |-- porting_lib_attributes 2.1.875+1.19.2
| |-- porting_lib_base 2.1.875+1.19.2
| |-- porting_lib_common 2.1.875+1.19.2
| |-- porting_lib_constants 2.1.875+1.19.2
| |-- porting_lib_entity 2.1.875+1.19.2
| |-- porting_lib_extensions 2.1.875+1.19.2
| |-- porting_lib_fake_players 2.1.875+1.19.2
| |-- porting_lib_lazy_registration 2.1.875+1.19.2
| |-- porting_lib_loot 2.1.875+1.19.2
| |-- porting_lib_model_generators 2.1.875+1.19.2
| |-- porting_lib_model_loader 2.1.875+1.19.2
| |-- porting_lib_models 2.1.875+1.19.2
| |-- porting_lib_networking 2.1.875+1.19.2
| |-- porting_lib_obj_loader 2.1.875+1.19.2
| |-- porting_lib_transfer 2.1.875+1.19.2
| \-- serialization_hooks 0.3.26
|-- reach-entity-attributes 2.3.0
\-- registrate-fabric 1.1.57-MC1.19.2
- create_crystal_clear 1.0+1.19.2
- creativecore 2.9.3
- creeperoverhaul 2.0.9
- croptopia 2.2.2
|-- com_typesafe_config 1.4.1
|-- io_leangen_geantyref_geantyref 1.3.11
|-- org_spongepowered_configurate-core 4.1.2
\-- org_spongepowered_configurate-hocon 4.1.2
- cryingghasts 3.1
- ctov 3.2.0
- customizableelytra 1.6.4-1.19
- cyanide 3.0.1
- dawn 3.5.0
- deeperdarker 1.1.6
|-- customportalapi 0.0.1-beta54-1.19
\-- paragon 3.0.2
\-- org_yaml_snakeyaml 1.27
- doubledoors 4.3
- dragonloot 1.1.2
- drinkbeer 3.2.2-1.19.2
- dungeon_difficulty 2.0.3+1.19
\-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
- dungeons_arise 2.1.54
- earthtojavamobs 1.9.3
- elytrautilities 2.0.0+1.19.2
\-- spectrelib 0.11.0+1.19
- endrem 5.2.0
- enhancedcelestials 2.1.0.5
- expandeddelight 0.2.5
- expandedstorage 8.3.0
- expert_armor 2.4
- extended_drawers 1.3.9+mc.1.19.2
|-- graphlib 0.3.6+1.19.2
\-- mconfig 1.2.0+mc.1.19-rc1
|-- de_poiu_apron_apron 2.1.1
\-- fabric-permissions-api-v0 0.1-SNAPSHOT
- fabric-api 0.76.0+1.19.2
|-- fabric-api-base 0.4.15+8f4e8eb390
|-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
|-- fabric-biome-api-v1 9.1.1+16f1e31390
|-- fabric-block-api-v1 1.0.2+e415d50e90
|-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
|-- fabric-client-tags-api-v1 1.0.5+b35fea8390
|-- fabric-command-api-v1 1.2.16+f71b366f90
|-- fabric-command-api-v2 2.2.1+413cbbc790
|-- fabric-commands-v0 0.2.33+df3654b390
|-- fabric-containers-v0 0.1.41+df3654b390
|-- fabric-content-registries-v0 3.5.2+7c6cd14d90
|-- fabric-convention-tags-v1 1.3.0+4bc6e26290
|-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
|-- fabric-data-generation-api-v1 5.3.8+413cbbc790
|-- fabric-dimensions-v1 2.1.35+0d0f210290
|-- fabric-entity-events-v1 1.5.4+9244241690
|-- fabric-events-interaction-v0 0.4.34+562bff6e90
|-- fabric-events-lifecycle-v0 0.2.36+df3654b390
|-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
|-- fabric-item-api-v1 1.6.6+b7d1888890
|-- fabric-item-groups-v0 0.3.39+9244241690
|-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
|-- fabric-keybindings-v0 0.2.23+df3654b390
|-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
|-- fabric-loot-api-v2 1.1.13+83a8659290
|-- fabric-loot-tables-v1 1.1.16+9e7660c690
|-- fabric-message-api-v1 5.0.7+93d8cb8290
|-- fabric-mining-level-api-v1 2.1.24+33fbc73890
|-- fabric-models-v0 0.3.21+c6af733c90
|-- fabric-networking-api-v1 1.2.11+10eb22f490
|-- fabric-networking-v0 0.3.28+df3654b390
|-- fabric-object-builder-api-v1 4.2.2+d8ef690890
|-- fabric-particles-v1 1.0.14+4d0d570390
|-- fabric-recipe-api-v1 1.0.1+413cbbc790
|-- fabric-registry-sync-v0 0.9.32+9244241690
|-- fabric-renderer-api-v1 1.2.1+1adbf27790
|-- fabric-renderer-indigo 0.8.0+1adbf27790
|-- fabric-renderer-registries-v1 3.2.24+df3654b390
|-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
|-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
|-- fabric-rendering-v0 1.1.27+df3654b390
|-- fabric-rendering-v1 1.12.1+d8ef690890
|-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
|-- fabric-resource-loader-v0 0.8.4+edbdcddb90
|-- fabric-screen-api-v1 1.0.32+4d0d570390
|-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
|-- fabric-sound-api-v1 1.0.2+c4f28df590
|-- fabric-textures-v0 1.0.24+aeb40ebe90
|-- fabric-transfer-api-v1 2.1.6+413cbbc790
\-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
- fabric-language-kotlin 1.9.3+kotlin.1.8.20
|-- org_jetbrains_kotlin_kotlin-reflect 1.8.20
|-- org_jetbrains_kotlin_kotlin-stdlib 1.8.20
|-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20
|-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20
|-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1
|-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
|-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
|-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
|-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
|-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
\-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
- fabric-tree-chopper 0.8.10
|-- fiber 0.23.0-2
\-- fiber2cloth 4.0.0
- fabricloader 0.14.19
- factory_blocks 1.0.0+1.19
- farmersdelight 1.19.2-1.3.9
- farmersknives 2.4
- fastload 3.3.7
|-- conditional-mixin 0.3.2
|-- fastload-119-0-1-2-compat 3.3.7
|-- fastload-1193-compat 3.3.7
|-- fastload-1194-compat 3.3.7
\-- fastload_fapi_forward 1.0.1
- fatxporbs 2.0.1
- ferritecore 5.0.3
- fishofthieves 2.2.3
- forgeconfigapiport 4.2.9
- frame 0.26.1+1.19-fabric
|-- frame-api-base 0.2.1+906ebc04a9
|-- frame-blocks-v0 0.1.3+233e7428a9
|-- frame-config-v0 0.3.1+0fa45150a9
|-- frame-content-registries-v0 0.4.0+2876b511a9
|-- frame-enchantments-v0 0.1.0+4093105da9
| \-- mm 2.3
|-- frame-game-rules-v0 0.2.4+e7ce56a6a9
|-- frame-items-v0 0.1.3+906ebc04a9
|-- frame-loot-tables-v0 0.1.4+4f7341eca9
|-- frame-registries-v0 0.1.1+0e0ec74ea9
|-- frame-rendering-v0 0.1.5+906ebc04a9
|-- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9
|-- frame-toymaker-v0 0.6.1+b13741c3a9
\-- frame-woods-v0 0.2.1+6a33fbada9
- frostiful 0.5.2
\-- mm 2.3
- gardens_of_the_dead 2.0.0
- geckolib3 3.1.40
\-- com_eliotlash_mclib_mclib 20
- geodes 1.7+1.19
- givemehat 2.5.0
- goodall 1.2.0
- graveyard 2.3
- harvest_scythes 2.5.4+mc1.19.2
\-- mm 2.3
- heartytrinkets 1.19-1.0.0
- icarus 1.14
- immersive_armors 1.5.5+1.19.2
- immersive_weathering 1.19.2-1.2.9
- impersonate 2.8.0
\-- fabric-permissions-api-v0 0.1-SNAPSHOT
- improved_end 1.19.2-1.0.6
- ingredient-extension-api 3.0.6
- interchangeable 1.1.0
- invview 1.4.9-1.19+
|-- fabric-permissions-api-v0 0.1-SNAPSHOT
\-- sgui 1.0.0-rc6+1.18-pre5
- java 17
- jline4mcdsrv 0.3.1
|-- com_moandjiezana_toml_toml4j 0.7.2
|-- org_fusesource_jansi_jansi 2.4.0
|-- org_jline_jline 3.21.0
\-- org_jline_jline-terminal-jansi 3.21.0
- kibe 1.9.11-BETA+1.19
- kiwi 8.3.3
- krypton 0.2.1
\-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
- labels 1.19.2-1.7
- lazydfu 0.1.3
- letsjeb 2.0.0
- lithium 0.11.1
- logbegone 1.0.4
- lychee 3.9.2
- mavapi 1.0.1
- mavm 1.2.0
- mca 7.4.8+1.19.2
- megane 8.4.0
|-- megane-alloy-forgery 8.4.0
|-- megane-api 8.4.0
|-- megane-applied-energistics-2 8.4.0
|-- megane-create 8.4.0
|-- megane-fabric-transfer 8.4.0
|-- megane-kibe 8.4.0
|-- megane-modern-dynamics 8.4.0
|-- megane-reborn-core 8.4.0
|-- megane-reborn-energy 8.4.0
|-- megane-runtime 8.4.0
|-- megane-tech-reborn 8.4.0
\-- megane-vanilla 8.4.0
- merequester 1.19.2-1.1.2
- midnightlib 1.0.0
- mimic 1.2.38
- minecells 1.4.3
\-- omega-config 1.2.3-1.18.1
- minecraft 1.19.2
- mixintrace 1.1.1+1.17
- modern_industrialization 1.6.5
|-- magna 1.8.0-1.19
\-- noindium 1.1.0+1.19
- moderndynamics 0.4.3-beta
- moonlight 1.19.2-2.2.31
- morefrogs 1.19.x-1.2.3-fabric
- moremobvariants 1.0.1
- multiworldborders 1.5-fabric-1.19
- musuen 1.2.3+fabric_1.19.2
\-- reach-entity-attributes 2.3.0
- mythicmetals 0.17.3+1.19.2
|-- additionalentityattributes 1.2.0+1.19
|-- cardinal-components-base 5.0.2
|-- cardinal-components-entity 5.0.2
\-- reach-entity-attributes 2.3.0
- nbtcrafting 2.2.3+mc1.19
- nochatreports 1.19.2-v1.13.12
|-- fabric-rendering-v1 1.11.0+73145abb90
\-- fabric-screen-api-v1 1.0.27+93d8cb8290
- not-that-cc 1.0
- nullscape 1.2.1
- nyfsquiver Fabric-0.5.1-1.19.2
\-- trinkets 3.5.0
|-- cardinal-components-base 5.0.2
\-- cardinal-components-entity 5.0.2
- owo 0.9.3+1.19
\-- blue_endless_jankson 1.2.1
- paradise_lost 2.1.0-beta+1.19.2
|-- customportalapi 0.0.1-beta54-1.19
|-- gud_recipe_confidence 1.0.2
|-- incubus_core 1.9.4
|-- reach-entity-attributes 2.3.0
\-- satin 1.8.0
- patchouli 1.19.2-77-FABRIC
\-- fiber 0.23.0-2
- paxi 1.19.2-Fabric-3.0.1
- pehkui 3.7.3+1.14.4-1.20
\-- kanos_config 0.4.0+1.14.4-1.19.4
- player-animator 1.0.2
- player_roles 1.6.1
|-- more_codecs 0.2.2+1.18
\-- player_roles_api 1.6.1
- playerabilitylib 1.6.0
- plushies 1.2
- polymorph 0.46.1+1.19.2
\-- spectrelib 0.11.0+1.19
- probablychests 0.5.5-1.19.2
- profundis 1.4.1
- projectile_damage 3.1.0+1.19
- puzzleslib 4.4.0
|-- cardinal-components-base 5.0.2
|-- cardinal-components-block 5.0.2
|-- cardinal-components-chunk 5.0.2
|-- cardinal-components-entity 5.0.2
\-- cardinal-components-world 5.0.2
- pyrotastic 1.19+2.0.3
- qcraft 1.2.0
\-- libgui 6.0.0+1.19
|-- jankson 4.1.1+j1.2.1
\-- libninepatch 1.1.0
- qu-enchantments 1.2.4-1.19
\-- mm 2.3
- quarrymod 1.0.3
- rainbowslime 1.1.3-1.19.2
- reborncore 5.4.0
\-- team_reborn_energy 2.3.0
- repurposed_structures 6.3.24+1.19.2
\-- com_github_llamalad7_mixinextras 0.2.0-beta.6
- resourcefulconfig 1.0.20
- resourcefullib 1.1.23
- restrictedportals 1.4.1
- revelationary 1.3.5
- riding_partners 1.0.0
- roughlyenoughitems 9.1.595
\-- error_notifier 1.0.9
- roughlyenoughprofessions 1.1.4
- roughlyenoughresources 2.6.0
- scarves 1.2.0
|-- libgui 6.0.0+1.19
| |-- jankson 4.1.1+j1.2.1
| \-- libninepatch 1.1.0
\-- pride 1.2.0+1.19
- sentimentality3 1.5.3-1.19.2
- serverping 1.2.0
\-- fiber 0.23.0-2
- shulkerboxtooltip 3.2.2+1.19.2
- simplyswords 1.43.0-1.19.2
- skylorlib 1.5.1
- slide_show 1.19.2-1.0.2
- smallernetherportals 3.4
- smallships 2.0.0a1.1.1
- smoothboot 1.19-1.7.1
- snowrealmagic 5.1.0
- soulsweapons 0.9.9.2
- spectrum 1.6.9-1.19.2-leisure_time
|-- arrowhead 1.2.0-1.19.2
|-- incubus_core 1.9.4
\-- reach-entity-attributes 2.3.0
- spellbound 1.10.0
- spelunkery 1.19.2-0.2.2
- spiceoffabric 1.6.0-beta.4+1.19.2
|-- capsaicin 1.3.1+mc1.19.3
|-- coat 1.0.0-beta.18+mc22w17a
|-- tweed4_annotated 1.3.1+mc22w17a
|-- tweed4_base 1.7.1+mc22w17a
|-- tweed4_data 1.2.1+mc22w17a
|-- tweed4_data_hjson 1.1.1+mc22w17a
|-- tweed4_tailor_coat 1.1.3+mc22w17a
\-- tweed4_tailor_screen 1.1.1+mc22w17a
- spiderstpo 1.19.2-2.0.3
- spirit 2.2.4
- sprout 1.4.4
- stackdeobfuscator 1.3.1+fabric.d71a3c3
\-- net_fabricmc_mapping-io 0.3.0
- starbidous_portal_linking 1.0.0
- starlight 1.1.1+fabric.ae22326
- styled-nicknames 1.1.2+1.19
|-- fabric-permissions-api-v0 0.1-SNAPSHOT
|-- placeholder-api 2.0.0-beta.3+1.19
\-- player-data-api 0.1.0+1.18
- suggestionproviderfix 1.0.0
- taxfreelevels 1.3.3
- techreborn 5.4.0
\-- team_reborn_energy 2.3.0
- terrablender 2.0.1.136
- terrestria 5.0.8
|-- terraform-biome-remapper-api-v1 4.2.0
|-- terraform-config-api-v1 4.2.0
|-- terraform-dirt-api-v1 4.2.0
|-- terraform-shapes-api-v1 4.2.0
|-- terraform-surfaces-api-v1 4.2.0
|-- terraform-tree-api-v1 4.2.0
|-- terraform-wood-api-v1 4.2.0
|-- terrestria-client 5.0.8
|-- terrestria-common 5.0.8
\-- terrestria-worldgen 5.0.8
- the_bumblezone 6.7.13+1.19.2
\-- fake-player-api 0.5.0
- thermoo 1.4
- things 0.3.0+1.19
\-- reach-entity-attributes 2.3.0
- timeoutout 1.0.3+1.19.1
- tlc 1.0.0
- toms_storage 1.5.4
- travelersbackpack 1.19.2-8.2.19
\-- reach-entity-attributes 2.3.0
- uselessreptile 0.2.0-1.19.2
- vanityslots 1.2.6
- vinery 1.2.3
\-- terraform-wood-api-v1 4.2.0
- visualoverhaul 4.1.1
- whisperwoods 1.19-2.1.1
- whyamionfire 1.2.0
- wondrouswilds 1.19.2-1.1.6
- wthit 5.15.2
- xaerominimap 23.4.0
- xaeroworldmap 1.30.0
- yet-another-config-lib 2.2.0-for-1.19.2
- yigd 1.4.9
- yungsapi 1.19.2-Fabric-3.8.9
\-- org_javassist_javassist 3.28.0-GA
```

**Logs:**
Occurs upon meeting the following exception:
```
[21:45:34] [main/ERROR]: Couldn't parse loot table immersive_weathering:blocks/croptopia/cinnamon_leaf_pile
[21:45:34] [main/ERROR]: com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'croptopia:cinnamon_leaves'
at MC//net.minecraft.util.JsonHelper.method_17995(JsonHelper.java:137)
at java.base@17.0.6/java.util.Optional.orElseThrow(Optional.java:403)
at MC//net.minecraft.util.JsonHelper.asItem(JsonHelper.java:137)
at MC//net.minecraft.util.JsonHelper.getItem(JsonHelper.java:145)
at MC//net.minecraft.loot.entry.ItemEntry$Serializer.fromJson(ItemEntry.java:55)
at MC//net.minecraft.loot.entry.ItemEntry$Serializer.fromJson(ItemEntry.java:40)
at MC//net.minecraft.loot.entry.LeafEntry$Serializer.fromJson(LeafEntry.java:151)
at MC//net.minecraft.loot.entry.LeafEntry$Serializer.fromJson(LeafEntry.java:129)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:86)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:74)
at MC//net.minecraft.util.JsonSerializing$GsonSerializer.deserialize(JsonSerializing.java:102)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.Gson.fromJson(Gson.java:963)
at com.google.gson.Gson.fromJson(Gson.java:1034)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:455)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:463)
at MC//net.minecraft.loot.entry.CombinedEntry$1.fromJson(CombinedEntry.java:61)
at MC//net.minecraft.loot.entry.CombinedEntry$1.fromJson(CombinedEntry.java:53)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:86)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:74)
at MC//net.minecraft.util.JsonSerializing$GsonSerializer.deserialize(JsonSerializing.java:102)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.Gson.fromJson(Gson.java:963)
at com.google.gson.Gson.fromJson(Gson.java:1034)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:455)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:463)
at MC//net.minecraft.loot.entry.CombinedEntry$1.fromJson(CombinedEntry.java:61)
at MC//net.minecraft.loot.entry.CombinedEntry$1.fromJson(CombinedEntry.java:53)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:86)
at MC//net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry.java:74)
at MC//net.minecraft.util.JsonSerializing$GsonSerializer.deserialize(JsonSerializing.java:102)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.Gson.fromJson(Gson.java:963)
at com.google.gson.Gson.fromJson(Gson.java:1034)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:455)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:463)
at MC//net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:173)
at MC//net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:169)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
at com.google.gson.Gson.fromJson(Gson.java:963)
at com.google.gson.Gson.fromJson(Gson.java:1034)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:455)
at MC//net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:473)
at MC//net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:214)
at MC//net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:210)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:963)
at com.google.gson.Gson.fromJson(Gson.java:1034)
at com.google.gson.Gson.fromJson(Gson.java:1006)
at MC//net.minecraft.loot.LootManager.method_20711(LootManager.java:44)
at java.base@17.0.6/java.util.HashMap.forEach(HashMap.java:1421)
at MC//net.minecraft.loot.LootManager.apply(LootManager.java:42)
at MC//net.minecraft.loot.LootManager.apply(LootManager.java:17)
at MC//net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13)
at java.base@17.0.6/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
at java.base@17.0.6/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at MC//net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:69)
at MC//net.minecraft.util.Util.waitAndApply(Util.java:958)
at MC//net.minecraft.util.Util.waitAndApply(Util.java:946)
at net.minecraft.server.Main.main(Main.java:156)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
```

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Start the game
2. Watch in despair

**Expected behavior:**
Server actually starts I guess

**Screenshots:**
*none*

**Additional info:**
Tbh I'd like to help, but cannot afford the time to really look into it, sorry.
I just hope this much is enough to figure out and fix the issue.

**Comment by NerjalNosk** [comment]
The stacktrace remapping is done by StackDeobfuscator, which I believe defaults down to Yarn mappings. Which while being more handy for me, might come at an issue for you, sorry about that.

**Comment by NerjalNosk** [comment]
Managed to narrow the culprit to `Restricted Portals` (hope that helps) -- gotta rename the issue btw

**Comment by NerjalNosk** [comment]
Further investigation makes me believe this is only a pure `Restricted Portals` issue, sorry for the wasted time.
