### ISSUE TITLE
Trying to place hanging roots crashes the game 

### ISSUE THREAD

**Issue by Talandar99** [AstralOrdana/Immersive-Weathering#399]
**Describe the bug:**
Trying to place hanging roots on on top or bottom of the block crashes the game
you can place them just fine on sides

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: immersive_weathering-1.19.2-1.2.10
Moonlight Lib version: moonlight-1.19.2-2.3.7
Fabric API / QSL / Forge version: net.minecraftforge:43.4.4

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
```java
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-10-05 14:09:00
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to up on Block{immersive_weathering:hanging_roots_wall}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading}
	at com.ordana.immersive_weathering.blocks.WallRootsBlock.m_5573_(WallRootsBlock.java:79) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23144!/:?] {re:classloading}
	at com.ordana.immersive_weathering.forge.CeilingAndWallBlockItem.m_5965_(CeilingAndWallBlockItem.java:27) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23144!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.4.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Immersive Weathering (immersive_weathering), Version: 1.19.2-1.2.10
		at TRANSFORMER/immersive_weathering@1.19.2-1.2.10/com.ordana.immersive_weathering.blocks.WallRootsBlock.m_5573_(WallRootsBlock.java:79)
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading}
	at com.ordana.immersive_weathering.blocks.WallRootsBlock.m_5573_(WallRootsBlock.java:79) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23144!/:?] {re:classloading}
	at com.ordana.immersive_weathering.forge.CeilingAndWallBlockItem.m_5965_(CeilingAndWallBlockItem.java:27) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23144!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Talandar_'/291, l='ClientLevel', x=-1.24, y=99.00, z=12.54]]
	Chunk stats: 729, 464
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,101,0), Section: (at 0,5,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1902 game time, 1902 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2280) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.4.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Immersive Weathering Generated Pack, Supplementaries Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.9.9-zen1-1-zen
	Java Version: 17.0.11, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 639636120 bytes (610 MiB) / 2617245696 bytes (2496 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3100 4-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 24354.80
	Virtual memory used (MB): 13239.69
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 2287.50
	JVM Flags: 2 total; -Xms1024m -Xmx10240m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 6600 (radeonsi, navi23, LLVM 18.1.8, DRM 3.57, 6.9.9-zen1-1-zen) GL version 4.6 (Core Profile) Mesa 24.1.3-arch1.1, AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 3 3100 4-Core Processor
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Talandar_'/291, l='ServerLevel[New World]', x=-1.24, y=99.00, z=12.54]]
	Data Packs: vanilla, mod:moonlight (incompatible), mod:forge, mod:immersive_weathering (incompatible), Immersive Weathering Generated Pack, mod:mixinextras (incompatible), mod:supplementaries (incompatible), Supplementaries Generated Pack
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mixinextras-forge-0.2.0-rc.5.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.5          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.7-forge(1).jar               |Moonlight Library             |moonlight                     |1.19.2-2.3.7        |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.4.4-universal.jar                 |Forge                         |forge                         |43.4.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		immersive_weathering-1.19.2-1.2.10-forge.jar      |Immersive Weathering          |immersive_weathering          |1.19.2-1.2.10       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.20.jar                 |Supplementaries               |supplementaries               |1.19.2-2.4.20       |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 591d23f4-4de1-4b32-9847-1842ddfb009e
	FML: 43.4
	Forge: net.minecraftforge:43.4.4
```
**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install minecraft 1.19.2 with newest forge version
2. Add moonlight lib, and immersive weathering
3. try to place hanging roots on top or bottom of the block

**Expected behavior:**
game should crash

**Additional info:**
logs sugest that the issue is occuring because your block is missing top and bottom placement options
i think that you wanted it to default to minecraft:hanging_roots and it's failing ;/

here we have only 4 directions and minecraft don't know what to do with other 2 
https://github.com/AstralOrdana/Immersive-Weathering/blob/c5501c2a74be36ddc272b224a19e9fd56d288874/common/src/main/java/com/ordana/immersive_weathering/blocks/WallRootsBlock.java#L29

we are using original minecraft:hanging_roots to place moded version so it's assume "down" direction exist
but according to this code it's not

**Comment by Untrustedlife** [comment]
Just ran into this. Really annoying
