### ISSUE TITLE
Recipes/loot tables not loading; StackOverflowError with CrackableBlock

### ISSUE THREAD

**Issue by cascadecollapse** [AstralOrdana/Immersive-Weathering#48]
Fabric 1.18.2, IW 2.3.0
While loading, log has multiple errors loading recipes:
```java
[9:48:96] [Render thread/ERROR]: Parsing error loading recipe immersive_weathering:prismarine_brick_wall
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:prismarine_brick_wall'
	at net.minecraft.class_1869.method_17878(class_1869.java:253)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_1869.method_8155(class_1869.java:253)
	at net.minecraft.class_1869.method_35228(class_1869.java:240)
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:273)
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260)
	at net.minecraft.class_1863.method_17720(class_1863.java:125)
	at net.minecraft.class_1863.method_20705(class_1863.java:54)
	at net.minecraft.class_1863.method_18788(class_1863.java:33)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
```
and loot tables:
```java
[9:48:22] [Render thread/ERROR]: Couldn't parse loot table immersive_weathering:blocks/forest_lichen
java.lang.IllegalArgumentException: Can't find block immersive_weathering:forest_lichen
	at net.minecraft.class_212$class_214.method_17937(class_212.java:79)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_212$class_214.method_910(class_212.java:79)
	at net.minecraft.class_212$class_214.method_517(class_212.java:68)
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
```
while playing in singleplayer, got a crash with this error as the culprit:
```java
java.lang.StackOverflowError
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
	at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:99)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2057)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1931)
	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2805)
	at org.apache.logging.log4j.spi.AbstractLogger.handleLogMessageException(AbstractLogger.java:2225)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2208)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907)
	at org.apache.logging.slf4j.Log4jLogger.warn(Log4jLogger.java:243)
	at net.minecraft.class_6396.method_37121(class_6396.java:83)
	at net.minecraft.class_6396.method_37128(class_6396.java:74)
	at net.minecraft.class_6396.method_37143(class_6396.java:51)
	at net.minecraft.class_6396.method_37121(class_6396.java:81)
	at net.minecraft.class_6396.<init>(class_6396.java:51)
	at net.minecraft.class_128.<init>(class_128.java:32)
	at net.minecraft.class_128.method_560(class_128.java:264)
	at net.minecraft.class_1937.method_8492(class_1937.java:358)
	at net.minecraft.class_1937.method_8452(class_1937.java:320)
	at net.minecraft.class_3218.method_8408(class_3218.java:1377)
	at net.minecraft.class_1937.method_30092(class_1937.java:235)
	at net.minecraft.class_1937.method_8652(class_1937.java:196)
	at net.minecraft.class_1937.method_8501(class_1937.java:311)
	at com.ordana.immersive_weathering.registry.blocks.crackable.CrackableBlock.method_9612(CrackableBlock.java:43)
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:884)
	at net.minecraft.class_1937.method_8492(class_1937.java:356)
	at net.minecraft.class_1937.method_8452(class_1937.java:320)
	at net.minecraft.class_3218.method_8408(class_3218.java:1377)
	at net.minecraft.class_1937.method_30092(class_1937.java:235)
	at net.minecraft.class_1937.method_8652(class_1937.java:196)
	at net.minecraft.class_1937.method_8501(class_1937.java:311)
	at com.ordana.immersive_weathering.registry.blocks.crackable.CrackableBlock.method_9612(CrackableBlock.java:43)
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:884)
	at net.minecraft.class_1937.method_8492(class_1937.java:356)
	at net.minecraft.class_1937.method_8452(class_1937.java:320)
	at net.minecraft.class_3218.method_8408(class_3218.java:1377)
	at net.minecraft.class_1937.method_30092(class_1937.java:235)
	at net.minecraft.class_1937.method_8652(class_1937.java:196)
	at net.minecraft.class_1937.method_8501(class_1937.java:311)
	at com.ordana.immersive_weathering.registry.blocks.crackable.CrackableBlock.method_9612(CrackableBlock.java:43)
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:884)
```
...and then it keeps going like that.

**Comment by AstralOrdana** [comment]
You are playing an outdated version.

**Comment by cascadecollapse** [comment]
> You are playing an outdated version.

oh, i see. i downloaded IW off of modrinth, 2.4.0 isn't on there, 2.3.0 is the featured version
