### ISSUE TITLE
V.2.5.0: NullPointerException causes Crash

### ISSUE THREAD

**Issue by Chribit** [AstralOrdana/Immersive-Weathering#64]
The following Null Pointer Exception is thrown and causes the game to crash randomly while playing. I do not know what action this crash explicitly correlates to unfortunately.

> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2394.method_10295()" because "$$0" is null
	at net.minecraft.class_638.method_8406(class_638.java:557)
	at net.minecraft.class_5945.method_34681(class_5945.java:52)
	at net.minecraft.class_5945.method_34682(class_5945.java:15)
	at net.minecraft.class_2397.handler$ddd000$randomDisplayTick(class_2397.java:1064)
	at net.minecraft.class_2397.method_9496(class_2397.java)
	at net.minecraft.class_638.method_2943(class_638.java:337)
	at net.minecraft.class_638.method_2941(class_638.java:313)
	at net.minecraft.class_310.method_1574(class_310.java:1802)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I've attached the full crash log to this issue as well, in case this turns out to be a mod compatibility issue. I use various performance mods as well as a plethora of world generation mods. I suspect the cause falls in either of these categories.

[crash-2022-05-27_09.15.23-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8784751/crash-2022-05-27_09.15.23-client.txt)

**Comment by AstralOrdana** [comment]
on a hunch, if you have any Falling Leaves mod installed, could you try removing it?

**Comment by Chribit** [comment]
I don‘t think I have any installed… I did see the falling leaves of this update though - so if they would be the issue, they would‘ve caused a crash (which they didn‘t).

I can describe a situation that did cause a crash though, but I don‘t know if anything else was going on in the background:

I was standing in a terralith brushland biome (so pretty arid, not to many leaves) and placing the sand piles, trying to create a smooth sandy slope…

I mean, it‘s not much of a lead - i could help investigate over the weekend if you want.

Sometimes a world crashes straight on spawn (new world), sometimes i can play for a minute or two…

**Comment by AstralOrdana** [comment]
do you have any mods that might add new types of leaves by chance?

**Comment by Chribit** [comment]
yes!

biome makeover and ecologics, betternether and betterend as well (not sure if immersive weathering applies to other dimensions)

**Comment by AstralOrdana** [comment]
fantastic, i know what the issue is then, will be pushing a fix shortly

**Comment by Chribit** [comment]
Glad i could help!
