### ISSUE TITLE
crash with betternether v2.5.1

### ISSUE THREAD

**Issue by JonCaver** [AstralOrdana/Immersive-Weathering#68]
the latest release 2.5.1 is causing an crash with betternether black vines. it works with the version 2.4.0 the one i was using prior to updating. is this something you can fix or should i post it on betternethers github?? Thank you for your time!

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/27/22, 7:19 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2746{name=persistent, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:black_vine}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.ordana.immersive_weathering.block_growth.hardcoded.LeavesGrowth.tryGrowing(LeavesGrowth.java:34)
	at com.ordana.immersive_weathering.block_growth.BlockGrowthHandler.tickBlock(BlockGrowthHandler.java:57)
	at net.minecraft.class_3218.handler$cfn000$tickBlocks(class_3218.java:7151)
	at net.minecraft.class_3218.method_18203(class_3218.java:489)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AstralOrdana** [comment]
this is a known issue, fix has already been pushed

**Comment by JonCaver** [comment]
Crash still present with v 2.5.2 it does effect a different block now but still crashes. 

---- Minecraft Crash Report ----
// You're mean.

Time: 5/27/22, 8:21 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2746{name=persistent, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:nether_reed_stem}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.ordana.immersive_weathering.block_growth.hardcoded.LeavesGrowth.tryGrowing(LeavesGrowth.java:34)
	at com.ordana.immersive_weathering.block_growth.BlockGrowthHandler.tickBlock(BlockGrowthHandler.java:57)
	at net.minecraft.class_3218.handler$cfn000$tickBlocks(class_3218.java:7151)
	at net.minecraft.class_3218.method_18203(class_3218.java:489)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
