### ISSUE TITLE
crash with betternether v2.5.2

### ISSUE THREAD

**Issue by JonCaver** [AstralOrdana/Immersive-Weathering#69]
Crash still present with v 2.5.2
It does effect a different block now but still crashes. I deleted the config to generate another just in case and still crashes whenever I am in the nether. 

---- Minecraft Crash Report ----
// You're mean.

Time: 5/27/22, 8:21 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2746{name=persistent, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:nether_reed_stem}
at net.minecraft.class_2688.method_11654(class_2688.java:98)
at com.ordana.immersive_weathering.block_growth.hardcoded.LeavesGrowth.tryGrowing(LeavesGrowth.java:34)
at com.ordana.immersive_weathering.block_growth.BlockGrowthHandler.tickBlock(BlockGrowthHandler.java:57)
at net.minecraft.class_3218.handler$cfn000$tickBlocks(class_3218.java:7151)
at net.minecraft.class_3218.method_18203(class_3218.java:489)
at net.minecraft.class_3215.method_14161(class_3215.java:378)
at net.minecraft.class_3215.method_12127(class_3215.java:322)
at net.minecraft.class_3218.method_18765(class_3218.java:311)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
at net.minecraft.class_1132.method_3748(class_1132.java:97)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
at java.base/java.lang.Thread.run(Thread.java:833)
@JonCaver

[https://github.com/AstralOrdana/Immersive-Weathering/issues/68](url)

**Comment by AstralOrdana** [comment]
report it to better nether, i've done everything i can on my end to fix it

**Comment by AstralOrdana** [comment]
nvm, no need i fixed it

**Comment by AstralOrdana** [comment]
could you confirm that this has been fixed on 2.5.3?

**Comment by Chribit** [comment]
I've been flying around my better-nether for a couple of minutes and everything seems to be working fine!

**Comment by JonCaver** [comment]
Can confirm it is fixed with the latest update 2.5.3!! Thank you very much for you time!!
