### ISSUE TITLE
[2.5.3] (different) NullPointerException causing game to crash

### ISSUE THREAD

**Issue by Chribit** [AstralOrdana/Immersive-Weathering#70]
Hey, it's me again lol.

Playing on Fabric Minecraft 1.18.2 with the mod version 2.5.3.

The Game definitely is much more stable, but I just wanted to see the frost mechanics at night and the game crashed on me again. This time the error log thankfully includes a specific cause:

> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because the return value of "net.minecraft.class_1750.method_8036()" is null
	at net.minecraft.class_2488.handler$bka000$corners$canReplace(class_2488.java:519)
	at net.minecraft.class_2488.method_9616(class_2488.java:1250)
	at net.minecraft.class_4970$class_4971.method_26166(class_4970.java:963)
	at net.minecraft.class_1750.<init>(class_1750.java:32)
	at net.minecraft.class_2968.<init>(class_2968.java:15)
	at com.ordana.immersive_weathering.registry.entities.FallingLeafLayerEntity.method_5773(FallingLeafLayerEntity.java:108)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
Since I was in a snowy taiga biome, I don't think this is due to a modded leaf block this time. But it was generating new chunks, so there may have been some in the distance I couldn't see.

I'll just disable the falling leaf layer in the config for the time being.

I've attached the full error log.

[crash-2022-05-28_10.18.05-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8790759/crash-2022-05-28_10.18.05-server.txt)

**Comment by Chribit** [comment]
I may have found the cause:

I recently installed the mod "the corners", which was marked as incompatibility with "snow! real magic".

Maybe "the corners" should be marked as an incompatibility for immersive weathering as well?

**Comment by MehVahdJukaar** [comment]
nah that's definitely a simple bug. Will be fixed. Also IW does not have anything to do with snow real magic apart from a mixin that applies directly do that mod since that's the only way that icicles can spawn when both are installed since srm nuked the vanilla method that was instead used

**Comment by Chribit** [comment]
Well removing „the corners“ seems to have fixed it for now, it‘s all running stable and beatifully :)
