### ISSUE TITLE
Unable to strip wood in 1.19 Fabric

### ISSUE THREAD

**Issue by georgno** [AstralOrdana/Immersive-Weathering#84]
Running the latest Fabric Server with fabric-api-0.55.3 and immersive_weathering-1.0.0-1.19

Getting this Error in the Serverlog when trying to strip a log
```java
[18:19:52] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@63e1494a, suppressing error
java.lang.ClassCastException: class java.util.Random cannot be cast to class net.minecraft.class_5819 (java.util.Random is in module java.base of loader 'bootstrap'; net.minecraft.class_5819 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3ec300f1)
        at com.ordana.immersive_weathering.registry.ModEvents.lambda$registerEvents$5(ModEvents.java:921) ~[immersive_weathering-1.0.0-1.19.jar:?]
        at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41) ~[fabric-events-interaction-v0-0.4+9ff28f40a9-b07890a27f424835.jar:?]
        at net.minecraft.class_3225.handler$zcg000$interactBlock(class_3225.java:585) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1115) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

The block doesn't get converted and I can forever rightclick it to get Birch Bark :smile:

**Comment by AstralOrdana** [comment]
do you have any other mods installed?

**Comment by georgno** [comment]
Okay just tested it. Removed all mods besides immersive weathering.
Sadly the bug still persists but I did find something else.
When I go in to creative mode I can remove the bark without any problems. But in Survival and Adventure mode the exception above gets thrown.
