### ISSUE TITLE
[1.18.2 - 2.5.5] Exception Ticking World: server crash due to bewitchment crop planted on mulch

### ISSUE THREAD

**Issue by Chribit** [AstralOrdana/Immersive-Weathering#92]
Hey,

My server is currently crashing due to me planting belladonna seeds (bewitchment mod) on mulch. The following error can be found in the logs:

```
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:911) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{bewitchment:belladonna}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[server-intermediary.jar:?]
	at com.ordana.immersive_weathering.registry.blocks.MulchBlock.method_9514(MulchBlock.java:104) ~[immersive_weathering-2.5.5.jar:?]
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.redirect$cjc000$redirectBlockStateTick(class_3218.java:12671) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18203(class_3218.java:486) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:378) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:322) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:311) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907) ~[server-intermediary.jar:?]
	... 5 more
```

Any idea how I could remove those blocks until you can bring out a fix (if you want to...)?

**Comment by AstralOrdana** [comment]
This is an issue with the bewitchment mod because the belladonna plant extends the vanilla crop type block but gives it a different amount of age values, leading to a crash. It is not possible for Immersive Weathering to account for every mod that uses this improper use of block classes. There is a config option that allows you to disable mulch's growth speed increase so you can re-join the game and remove the belladonna plants.

**Comment by Chribit** [comment]
Ah, how unfortunate! Thanks for the pointer, i‘ll just be disabling the growth speed increase in the config then.

**Comment by Karvoo** [comment]
> This is an issue with the bewitchment mod because the belladonna plant extends the vanilla crop type block but gives it a different amount of age values, leading to a crash. It is not possible for Immersive Weathering to account for every mod that uses this improper use of block classes. There is a config option that allows you to disable mulch's growth speed increase so you can re-join the game and remove the belladonna plants.

Just wanting further clarification on your advice above as I am dealing with the same issue. Are you saying the issue should be fixed by disabling mulch's growth speed in the config, or that we should do that to buy us time enough to load in before a crash and completely remove the affected mulch/seeds?

**Comment by AstralOrdana** [comment]
Disabling Mulch's growth speed increase will make it so that this crash can not occur. If you remove the belladonna seeds and then re-enable the speed increase, everything will work as intended.

**Comment by Karvoo** [comment]
Thank you so much!
